---
server:
  port: 8083

spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/albums?useSSL=false
    username: root

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG


s3:
  accessKey: VYY72EI3VF67D6A7AAEA
  secretKey: M9HNDgqGIFh/rjcy4dlnwZMEG28f0/wh8gZO8Ock
  bucketName: moviefun
  endPointUrl: http://127.0.0.1:9000


